/* this is generated by nino */
namespace TaoTie
{
    public partial class IngredientCategory
    {
        public static IngredientCategory.SerializationHelper NinoSerializationHelper = new IngredientCategory.SerializationHelper();
        public class SerializationHelper: Nino.Serialization.NinoWrapperBase<IngredientCategory>
        {
            #region NINO_CODEGEN
            public override void Serialize(IngredientCategory value, Nino.Serialization.Writer writer)
            {
                if(value == null)
                {
                    writer.Write(false);
                    return;
                }
                writer.Write(true);
                if(value.list != null)
                {
                    writer.Write(true);
                    writer.CompressAndWrite(value.list.Count);
                    foreach (var entry in value.list)
                    {
                        TaoTie.Ingredient.NinoSerializationHelper.Serialize(entry, writer);
                    }
                }
                else
                {
                    writer.Write(false);
                }
            }

            public override IngredientCategory Deserialize(Nino.Serialization.Reader reader)
            {
                if(!reader.ReadBool())
                    return null;
                IngredientCategory value = new IngredientCategory();
                if(reader.ReadBool()){value.list = new System.Collections.Generic.List<TaoTie.Ingredient>(reader.ReadLength());
                for(int i = 0, cnt = value.list.Capacity; i < cnt; i++)
                {
                    var value_list_i = TaoTie.Ingredient.NinoSerializationHelper.Deserialize(reader);
                    value.list.Add(value_list_i);
                }}
                return value;
            }
            #endregion
        }
    }
}